name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GCP_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add GCP host to known_hosts
      run: ssh-keyscan -H ${{ secrets.GCP_HOST }} >> ~/.ssh/known_hosts

    - name: Connect to GCP VM and run command
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }} "echo '✅ Connected to GCP!' && hostname && uptime"
